blank_issues_enabled: false
contact_links:
  - name: Discord Community
    url: https://discord.gg/SCtMCgtsc4
    about: Join our Discord for real-time help and discussions
  - name: Documentation
    url: https://cleanuparr.github.io/Cleanuparr/
    about: Check the documentation for configurations and usage guidelines