export const PushoverSounds = [
  { value: 'pushover', label: 'Pushover (Default)' },
  { value: 'bike', label: 'Bike' },
  { value: 'bugle', label: 'Bugle' },
  { value: 'cashregister', label: 'Cash Register' },
  { value: 'classical', label: 'Classical' },
  { value: 'cosmic', label: 'Cosmic' },
  { value: 'falling', label: 'Falling' },
  { value: 'gamelan', label: 'Gamelan' },
  { value: 'incoming', label: 'Incoming' },
  { value: 'intermission', label: 'Intermission' },
  { value: 'magic', label: 'Magic' },
  { value: 'mechanical', label: 'Mechanical' },
  { value: 'pianobar', label: 'Piano Bar' },
  { value: 'siren', label: 'Siren' },
  { value: 'spacealarm', label: 'Space Alarm' },
  { value: 'tugboat', label: 'Tugboat' },
  { value: 'alien', label: 'Alien (Long)' },
  { value: 'climb', label: 'Climb (Long)' },
  { value: 'persistent', label: 'Persistent (Long)' },
  { value: 'echo', label: 'Echo (Long)' },
  { value: 'updown', label: 'Up Down (Long)' },
  { value: 'vibrate', label: 'Vibrate Only' },
  { value: 'none', label: 'Silent' }
] as const;
