on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: flmorg/universal-workflows-testing/.github/workflows/dotnet.build.app.yml@main
    with:
      dockerRepository: flaminel/cleanuperr
      githubContext: ${{ toJSON(github) }}
      outputName: cleanuperr
      selfContained: false
      baseImage: 9.0-bookworm-slim
    secrets: inherit